export type { Patient, Gender, Vitals, Diagnosis, Medication, Encounter, Bed, LabOrder, MedicationOrder, NurseNote, PhysicianOrder, RadiologyOrder, SurgeryOrder, RespiratoryOrder, DietOrder, SocialWorkNote, EdTriage, MedicalChart, Charge, InsuranceClaim, Payment, InventoryItem, StockTransaction, BloodType, Rhesus } from "./patient/schema.js";
export { generatePatient, generatePatientPool } from "./patient/generator.js";
export { createClock, tick, formatHospitalTime } from "./engine/clock.js";
export { EventQueue } from "./engine/event-queue.js";
export { createState } from "./engine/state-store.js";
export { createWorld, step, runWorld } from "./engine/world.js";
export type { World } from "./engine/world.js";
export { createRestServer } from "./api/rest.js";
export { createFhirEndpoints } from "./api/fhir.js";
export { generateReport } from "./engine/report.js";
export { generateSirsReport, RS_IDENTITY } from "./engine/sirs-report.js";
export type { SirsReportBundle } from "./engine/sirs-report.js";
export { generateIdentity } from "./identity/generator.js";
export { generateAgent, generateAgentPool } from "./agent/generator.js";
export { agentHandler } from "./agent/system.js";
export { referralHandler, initReferralState } from "./referral/system.js";
export { PROVINCES, REFERRAL_FACILITIES } from "./identity/data.js";
